services:
  db:
    image: postgres:15-alpine
    volumes:
      - database:/data/db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}=value
  api:
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DB_HOST: ${DB_HOST}
volumes:
  database: